apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: observability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-a # Service와 매칭
  template:
    metadata:
      labels:
        app: app-a # Service와 매칭
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: observability-app
          image: 172.26.31.229:5000/observability-nodejs:latest
          ports:
            - containerPort: 8080 # Service의 targetPort와 매칭
          envFrom:
          - configMapRef:
              name: observability-app-a-config
