apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-app-b-config
  namespace: observability
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-master.postgres"
  DB_PORT: "5432"
  APP_HOST: "nodejs-app-b.observability"
  TARGET_ONE_HOST: "nodejs-app-a.observability"
  TARGET_TWO_HOST: "nodejs-app-c.observability"
  REDIS_HOST: "redis-master.redis"

