apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-a
  namespace: observability
  labels:
    app: app-a
spec:
  type: NodePort
  selector: # Pod와 연결될 레이블
    app: app-a
  ports:
    - protocol: TCP
      port: 8080       # 클러스터 내부용
      targetPort: 8080  # 컨테이너 포트
      nodePort: 30800 # 외부 접근용