apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-app-b-config
  namespace: observability
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-master.postgres"
  DB_PORT: "5432"
  APP_HOST: "http://nodejs-app-b.observability:8081"
  TARGET_ONE_HOST: "http://nodejs-app-a.observability:8080"
  TARGET_TWO_HOST: "http://nodejs-app-c.observability:8082"
  REDIS_HOST: "redis-master.redis"
  OTEL_SERVICE_NAME: "app-b"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.observability:4317"
