apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  namespace: observability
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-c # Service와 매칭
  template:
    metadata:
      labels:
        app: app-c # Service와 매칭
    spec:
      containers:
        - name: observability-app
          image: 172.26.31.229:5000/observability-nodejs:latest
          ports:
            - containerPort: 8082 # Service의 targetPort와 매칭
          envFrom:
          - configMapRef:
              name: observability-app-c-config
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: REDIS_PASSWORD