apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-b
  namespace: observability
  labels:
    app: app-b
spec:
  type: ClusterIP
  selector: # Pod와 연결될 레이블
    app: app-b
  ports:
    - protocol: TCP
      port: 8081       # 클러스터 내부용
      targetPort: 8080  # 컨테이너 포트