apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: observability
spec:
  storageClassName: "minio"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/minio # 노드의 로컬 디렉토리
