apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/loki/chunks/0 # 노드에서 고유 디렉토리 경로
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/loki/chunks/1 # 노드에서 고유 디렉토리 경로
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/loki/chunks/2 # 노드에서 고유 디렉토리 경로
