apiVersion: v1
kind: Service
metadata:
  name: observability-front
  namespace: observability
  labels:
    app: observability-front
spec:
  type: NodePort
  selector: # Pod와 연결될 레이블
    app: observability-front
  ports:
    - protocol: TCP
      port: 80        # 클러스터 내부용
      targetPort: 80  # 컨테이너 포트
      nodePort: 30007 # 외부 접근용