#version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false  # 보안 설정 비활성화 (개발용)
    ports:
      - "9200:9200"
    networks:
      - monitoring
    privileged: true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - monitoring
    depends_on:
      - elasticsearch
    privileged: true

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.3
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTIC_PASSWORD=changeme
    networks:
      - monitoring
    depends_on:
      - elasticsearch


  apm-server:
    image: docker.elastic.co/apm/apm-server:8.15.3
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - setup.kibana.host=http://kibana:5601
      - apm-server.metrics.enabled=true  # 메트릭 수집 기능 활성화
    ports:
      - "8200:8200"  # APM 서버 포트
    networks:
      - monitoring
    depends_on:
      - elasticsearch

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 1888:1888  # pprof extension
      - 8888:8888  # Prometheus metrics exposed by the Collector
      - 8889:8889  # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317  # OTLP gRPC receiver
      - 4318:4318  # OTLP http receiver
      - 55679:55679 # zpages extension
    environment:
      - RECEIVER_ENDPOINT=0.0.0.0:4317
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - monitoring

  app-a:
    image: ghcr.io/blueswen/spring-boot-observability/app:latest
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      - TARGET_ONE_HOST=app-b
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=app-a
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_METRICS_ENABLED=true
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
      - OTEL_METRICS_EXPORT_INTERVAL=30000
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-a
      - MANAGEMENT_METRICS_TAGS_APPLICATION=app-a
      - JAVA_TOOL_OPTIONS="-javaagent:/etc/opentelemetry-javaagent.jar"
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - otel-collector
      - apm-server

  app-b:
    image: ghcr.io/blueswen/spring-boot-observability/app:latest
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      - TARGET_ONE_HOST=app-b
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=app-b
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-b
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_METRICS_ENABLED=true
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
      - OTEL_METRICS_EXPORT_INTERVAL=30000
      - MANAGEMENT_METRICS_TAGS_APPLICATION=app-b
      - JAVA_TOOL_OPTIONS="-javaagent:/etc/opentelemetry-javaagent.jar"
    ports:
      - "8081:8080"
    networks:
      - monitoring
    depends_on:
      - otel-collector
      - apm-server

  app-c:
    image: ghcr.io/blueswen/spring-boot-observability/app:latest
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      - TARGET_ONE_HOST=app-b
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=app-c
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-c
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_METRICS_ENABLED=true
      - OTEL_INSTRUMENTATION_JVM_METRICS_ENABLED=true
      - OTEL_METRICS_EXPORT_INTERVAL=30000
      - MANAGEMENT_METRICS_TAGS_APPLICATION=app-c
      - JAVA_TOOL_OPTIONS="-javaagent:/etc/opentelemetry-javaagent.jar"
    ports:
      - "8082:8080"
    networks:
      - monitoring
    depends_on:
      - otel-collector
      - apm-server

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - monitoring

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
