global:
  scrape_interval: 15s

scrape_configs:
#  - job_name: 'app-a'
#    scrape_interval: 5s
#    metrics_path: "/metrics"
#    static_configs:
#      - targets: [ 'app-a:8080' ]

storage:
  exemplars:
    max_exemplars: 100000 # 저장 가능한 최대 Exemplars 개수
