global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app-a'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'app-a:8080' ]

  - job_name: 'app-b'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'app-b:8080' ]

  - job_name: 'app-c'
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'app-c:8080' ]

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:4317']

storage:
  exemplars:
    max_exemplars: 100000 # 저장 가능한 최대 Exemplars 개수