services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-wal:/wal
      - loki-chunks:/loki/chunks
      - loki-index:/loki/index
    user: "1000:1000"
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo.yaml
      - tempo-wal:/var/tempo/wal
      - tempo-blocks:/var/tempo/blocks
    environment:
      - STORAGE_LOCAL_PATH=/var/tempo/blocks
      - METRICS_GENERATOR_STORAGE_PATH=/var/tempo/generator/wal
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    user: "root:root"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
#      - GF_AUTH_API_KEY_ENABLED=true
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_PASSWORD=1Q2w3e4r1!
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
      - tempo

  app-front:
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - monitoring
  app-a:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=postgres
      - TARGET_ONE_HOST=app-b
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-a
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=app-a # service name for Span
    command: >
        node --require @opentelemetry/auto-instrumentations-node/register dist/app.js
    ports:
      - "8080:8080"
    networks:
      - monitoring
    depends_on:
      - node-exporter
      - otel-collector
      - postgres

  app-b:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=postgres
      - TARGET_ONE_HOST=app-a
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-b
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=app-b # service name for Span
    command: >
        node --require @opentelemetry/auto-instrumentations-node/register dist/app.js
    ports:
      - "8081:8080"
    networks:
      - monitoring
    depends_on:
      - node-exporter
      - otel-collector
      - postgres

  app-c:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=postgres
      - TARGET_ONE_HOST=app-a
      - TARGET_TWO_HOST=app-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=compose_service=app-c
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=app-c # service name for Span
    command: >
        node --require @opentelemetry/auto-instrumentations-node/register dist/app.js
    ports:
      - "8082:8080"
    networks:
      - monitoring
    depends_on:
      - node-exporter
      - otel-collector
      - postgres

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - monitoring

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
volumes:
  loki-wal:
  loki-chunks:
  loki-index:
  tempo-wal:
  tempo-blocks:
  grafana-data:
