receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']  # Node Exporter의 주소

processors:

exporters:
  debug:
    verbosity: basic #detailed, expensive
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true
  otlphttp:
    endpoint: "http://loki:3100/otlp"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp, debug]
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheusremotewrite, debug]
