apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-front
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    -  http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: observability-front
                port:
                  number: 80
