{
 "title": "New dashboard",
 "description": "for testing",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "[app-a] loki logs",
   "type": "logs",
   "description": "app-a 애플리케이션의 loki log를 보여줍니다.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app-a\"}"
    }
   ]
  },
  {
   "title": "[app-b] loki logs",
   "type": "logs",
   "description": "app-b 애플리케이션의 loki log를 보여줍니다.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app-b\"}"
    }
   ]
  },
  {
   "title": "[app-c] loki logs",
   "type": "logs",
   "description": "app-c 애플리케이션의 loki log를 보여줍니다.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"app-c\"}"
    }
   ]
  }
 ]
}