apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: otel-collector
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-12-17T00:17:28Z"
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.115.1
    component: standalone-collector
    helm.sh/chart: opentelemetry-collector-0.111.0
  name: otel-collector
  namespace: monitoring
  resourceVersion: "191337"
  uid: 06cefc14-8a49-4ea1-8db5-8b8ef323021a
spec:
  clusterIP: 10.233.23.244
  clusterIPs:
  - 10.233.23.244
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: jaeger-thrift
    port: 14268
    protocol: TCP
    targetPort: 14268
  - appProtocol: grpc
    name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app.kubernetes.io/instance: otel-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
