apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: http://prometheus-server.monitoring:9090/api/v1/write
        tls:
          insecure: true
      loki:
        endpoint: http://loki.logging:3100/loki/api/v1/push
        labels:
          service: "app-app"

      otlp:
        endpoint: tempo.tracing:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]

