apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-replica
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage-replica
  hostPath:
    path: "/tmp/data/redis-replica"  # 로컬 경로
    type: DirectoryOrCreate
