auth:
  enabled: true                 # Redis 인증 활성화
  password: redispassword          # Redis 비밀번호 설정

volumePermissions:
  enabled: true

replica:
  replicaCount: 1               # Replica Pod 개수
  persistence:
    enabled: true               # Replica의 데이터 지속성 활성화
    size: 5Gi                   # Replica의 PersistentVolume 크기
    storageClass: redis-storage-replica
    accessModes:
      - ReadWriteOnce
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Delete

master:
  persistence:
    enabled: true               # Master의 데이터 지속성 활성화
    size: 5Gi                   # Master의 PersistentVolume 크기
    storageClass: redis-storage
    accessModes:
      - ReadWriteOnce
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Delete