apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/grafana # 로컬 노드 경로 (운영 환경에서는 NFS, EBS 등을 사용 권장)
  storageClassName: grafana-storage