apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               md5
    host    replication     postgres        0.0.0.0/0               md5

  postgresql.conf: |
    # PostgreSQL configuration
    listen_addresses = '*'
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    archive_mode = on
    archive_command = 'cp %p /var/lib/postgresql/data/archive/%f'
