apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64로 인코딩된 "postgres"
  POSTGRES_REPLICATION_PASSWORD: cG9zdGdyZXM=  # base64로 인코딩된 "postgres"
