apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: postgres
spec:
  clusterIP: None  # Headless Service
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-replica
