apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
  namespace: postgres
spec:
  serviceName: "postgres-master"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-master
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          # 설정 파일을 마운트할 추가 볼륨
          volumeMounts:
            - name: postgres-config
              mountPath: /etc/postgresql-config
              readOnly: true
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc-master
        - name: postgres-config
          configMap:
            name: postgres-config

